version: "3.8"

services:
  # backend:
  #   build: .
  #   container_name: backend
  #   ports:
  #     - "4000:4000"
  #   env_file:
  #     - .env
  #   environment:
  #     - MONGO_URL=mongodb://mongo:27017/natours
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: natours
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
